#!/usr/bin/env php
<?php
set_time_limit(0);

require dirname(__FILE__).'/../bootstrap.php';

use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new Command\ListGetCommand($container));
$app->run();
